modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Lykrast/GunsWithoutRosesAdditions/issues"
license="MIT License https://github.com/Lykrast/GunsWithoutRosesAdditions/blob/master/LICENSE"

[[mods]]
modId="gunswithoutrosesadditions"
version="${file.jarVersion}"
displayName="Guns Without Roses Additions"
displayURL="https://modrinth.com/mod/guns-without-roses-additions"
logoFile="logo.png"
credits=""
authors="Lykrast"
description='''
Compatibility between Guns Without Roses and an assortment of random mods.
'''

[[dependencies.gunswithoutrosesadditions]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunswithoutrosesadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunswithoutrosesadditions]]
    modId="gunswithoutroses"
    mandatory=true
    versionRange="[1.20.1-2.4.0,)"
    ordering="AFTER"
    side="BOTH"