modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Lykrast/GunsWithoutRosesAdditions/issues"
license="MIT License https://github.com/Lykrast/GunsWithoutRosesAdditions/blob/master/LICENSE"

[[mods]]
modId="gunswithoutrosesadditions"
version="${file.jarVersion}"
displayName="Guns Without Roses Additions"
displayURL="https://www.curseforge.com/minecraft/mc-mods/guns-without-roses-additions"
credits=""
authors="Lykrast"
description='''
Compatibility between Guns Without Roses and an assortment of random mods.
'''

[[dependencies.gunswithoutrosesadditions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunswithoutrosesadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunswithoutrosesadditions]]
    modId="gunswithoutroses"
    mandatory=true
    versionRange="[1.18.2-1.0.14,)"
    ordering="AFTER"
    side="BOTH"